name: Waves-ui version verify

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  outdated :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do c√≥digo
      uses: actions/checkout@v2

    steps:
    - name: Hello
      run: echo "Hello ${{ inputs.name }}"
